name: Api service build and push
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "api-service"
jobs:
  build-and-push:
    name: Api service build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to ghcr
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_SITE_ORIGIN: https://next.titorelli.ru
          envkey_YANDEX_FUNCTION_URL: ${{secrets.YANDEX_FUNCTION_URL}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_TELEMETRY_DB_FILENAME: data/telemetry.sqlite
          envkey_MARKUP_DB_FILENAME: data/markup.sqlite
          envkey_DOCKHOST_TOKEN: ${{secrets.DOCKHOST_TOKEN}}
      - name: Build and push
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ghcr.io/titorelli-org/${{env.IMAGE_NAME}}
      - name: Artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{env.REGISTRY}}/titorelli-org/${{env.IMAGE_NAME}}
          subject-digest: ${{steps.push.outputs.digest}}
          push-to-registry: true
